{
 "title": "KTXOLIVI2",
 "time": { "from": "now-21h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "Grafana", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 11, "w": 10, "x": 0, "y": 1 },
   "options": {
    "content": "<iframe type=\"text/html\" frameborder=\"0\" width=\"100%\" height=\"100%\" src=\"//video.nest.com/embedded/live/hSbdKv5pcO?autoplay=1\" allowfullscreen></iframe>"
   }
  },
  {
   "title": "Pier Temp",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tmp",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "PID", "operator": "=", "value": "e00fce688bc49ce80a48871b" }
     ]
    }
   ]
  },
  {
   "title": "Battery Level",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "BBatC",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "PID", "operator": "=", "value": "e00fce688bc49ce80a48871b" }
     ]
    }
   ]
  },
  {
   "title": "Power Source",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "BPowSrc",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "PID", "operator": "=", "value": "e00fce688bc49ce80a48871b" }
     ]
    }
   ]
  },
  {
   "title": "Battery State",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "BBatSS",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "PID", "operator": "=", "value": "e00fce688bc49ce80a48871b" }
     ]
    }
   ]
  },
  {
   "title": "Tank 3 - Water Level Avg",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 14, "x": 10, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "lengthft" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "WAvg",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "PID", "operator": "=", "value": "e00fce688bc49ce80a48871b" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "WHigh",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "PID", "operator": "=", "value": "e00fce688bc49ce80a48871b" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "WLow",
     "query": "SELECT last(\"value\") FROM \"WaterLevelLow\" WHERE (\"PID\" = 'e00fce688bc49ce80a48871b') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "PID", "operator": "=", "value": "e00fce688bc49ce80a48871b" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 11, "w": 10, "x": 0, "y": 12 },
   "options": {
    "content": "<iframe type=\"text/html\" frameborder=\"0\" width=\"100%\" height=\"100%\" src=\"//video.nest.com/embedded/live/Ged4rX27Ao?autoplay=1\" allowfullscreen></iframe>"
   }
  },
  {
   "title": "Wave Height",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 14, "x": 10, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "lengthin" } },
   "targets": [
    { "expression": "$D * 12\n", "type": "math" }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 23 },
   "options": {
    "content": "<iframe width=\"100%T\" height=\"100%\" src=\"https://embed.windy.com/embed2.html?lat=28.628&lon=-93.625&zoom=5&level=surface&overlay=wind&menu=&message=&marker=&calendar=&pressure=&type=map&location=coordinates&detail=&detailLat=28.636&detailLon=-96.458&metricWind=default&metricTemp=default&radarRange=-1\" frameborder=\"0\"></iframe>"
   }
  },
  {
   "title": "Wind Speed",
   "type": "graph",
   "gridPos": { "h": 10, "w": 14, "x": 10, "y": 30 },
   "yaxes": [
    { "format": "velocitymph" }
   ],
   "targets": [
    {
     "target": "alias(wu.KTXOLIVI.avgwind, 'Wind')"
    },
    {
     "target": "alias(wu.KTXOLIVI.gustspeed, 'Gust')"
    },
    {
     "target": "alias(wu.KTXOLIVI.dailygust, 'DailyGust')"
    }
   ]
  },
  {
   "title": "Wind Direction",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "wu.KTXOLIVI.windir" }
   ]
  },
  {
   "title": "Temp",
   "type": "graph",
   "gridPos": { "h": 9, "w": 14, "x": 10, "y": 40 },
   "yaxes": [
    { "format": "farenheit" }
   ],
   "targets": [
    {
     "target": "alias(wu.KTXOLIVI.outTemp, 'WeatherStation')"
    },
    {
     "alias": "Bay Bathroom",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tmp",
     "query": "SELECT mean(\"value\") FROM \"temperature\" WHERE $timeFilter GROUP BY time(1s), \"deviceName\" fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "PID", "operator": "=", "value": "e00fce688bc49ce80a48871b" }
     ]
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "humidity" }
   ],
   "targets": [
    {
     "target": "alias(wu.KTXOLIVI.outHumi, 'Humidity')"
    },
    {
     "alias": "BORON",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hum",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Rain Levels",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "wu.KTXOLIVI.rainofdaily" },
    { "target": "wu.KTXOLIVI.rainofhourly" }
   ]
  },
  {
   "title": "Water Levels",
   "type": "graph",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(wu.KTXOLIVI.noaa.portlavaca.WaterLevel2, 'Port Lavaca')"
    },
    {
     "target": "alias(wu.KTXOLIVI.noaa.portoconner.WaterLevel2, 'Port Oconner')"
    },
    {
     "alias": "Pancamo Point",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "WAvg",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "-3" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "graph",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "pressurehpa" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "PID" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "alt",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "PID", "operator": "=", "value": "e00fce688bc49ce80a48871b" }
     ]
    }
   ]
  },
  {
   "title": "Solar Radation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 57 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "target": "alias(wu.KTXOLIVI.solarrad, 'Solar Radiation watts m^2')"
    }
   ]
  },
  {
   "title": "Battery Charge",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "BBatC",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "PID", "operator": "=", "value": "e00fce688bc49ce80a48871b" }
     ]
    }
   ]
  }
 ]
}