{
 "title": "Tideman2",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Water High",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 0 },
   "format": "lengthft",
   "valueName": "avg",
   "targets": [
    { "target": "wu.KTXOLIVI.PI2.WaterLevelHigh" }
   ]
  },
  {
   "title": "TideMan 2.0",
   "type": "graph",
   "gridPos": { "h": 10, "w": 19, "x": 5, "y": 0 },
   "yaxes": [
    { "format": "lengthft" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(wu.KTXOLIVI.PI2.WaterLevelHigh)"
    },
    {
     "target": "aliasByMetric(wu.KTXOLIVI.PI2.WaterLevelLow)"
    },
    {
     "target": "aliasByMetric(wu.KTXOLIVI.PI2.WaterLevelAvg)"
    }
   ]
  },
  {
   "title": "Water Low",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 2 },
   "format": "lengthft",
   "valueName": "avg",
   "targets": [
    { "target": "wu.KTXOLIVI.PI2.WaterLevelLow" }
   ]
  },
  {
   "title": "Wave Height  (in)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "target": "wu.KTXOLIVI.PI2.WaveHeight" }
   ]
  },
  {
   "title": "Cpu Temp",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "farenheit" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(wu.KTXOLIVI.PI2.CpuTemp)"
    }
   ]
  },
  {
   "title": "Wave Height inches",
   "type": "graph",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 10 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(wu.KTXOLIVI.PI2.WaveHeight)"
    }
   ]
  },
  {
   "title": "Cpu Util",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(wu.KTXOLIVI.PI2.CpuUtil)"
    }
   ]
  }
 ]
}