{
 "title": "Tideman2",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Water High",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "format": "lengthft",
   "valueName": "current",
   "targets": [
    { "target": "wu.KTXOLIVI.PI2.WaterLevelHigh" }
   ]
  },
  {
   "title": "TideMan 2.0",
   "type": "graph",
   "gridPos": { "h": 9, "w": 20, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "lengthft" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(wu.KTXOLIVI.PI2.WaterLevelHigh)"
    },
    {
     "target": "aliasByMetric(wu.KTXOLIVI.PI2.WaterLevelLow)"
    },
    {
     "target": "aliasByMetric(wu.KTXOLIVI.PI2.WaterLevelAvg)"
    }
   ]
  },
  {
   "title": "Water Low",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 3 },
   "format": "lengthft",
   "valueName": "current",
   "targets": [
    { "target": "wu.KTXOLIVI.PI2.WaterLevelLow" }
   ]
  },
  {
   "title": "Wave Height",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 6 },
   "format": "lengthft",
   "valueName": "current",
   "targets": [
    { "target": "wu.KTXOLIVI.PI2.WaveHeight" }
   ]
  },
  {
   "title": "Cpu Temp",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "farenheit" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(wu.KTXOLIVI.PI2.CpuTemp)"
    }
   ]
  },
  {
   "title": "Wave Height inches",
   "type": "graph",
   "gridPos": { "h": 5, "w": 20, "x": 4, "y": 9 },
   "yaxes": [
    { "format": "lengthft" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(wu.KTXOLIVI.PI2.WaveHeight)"
    }
   ]
  }
 ]
}